services:
  mongo:
    image: mongo
    restart: always
    ports: 
      - 27017:27017
    volumes:
      - cerradogo:/home/node/app
    environment:
      MONGO_INITDB_ROOT_USERNAME: cerradogo
      MONGO_INITDB_ROOT_PASSWORD: 6AzwKPCI9Z7iXcLu
volumes:
  cerradogo:
    external: false
